<div class="alert alert-block alert-danger">   
<p style="padding:50px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:50px;text-align:center;border-radius: 00px 00px;overflow:hidden;font-weight:500">Numpy Tutorial</p></div> 

<strong><font color=b16e0d> In this Notebook we can learn Numpy: </font><strong><br>
- What is NumPy Library and how to import NumPy Library.
- Difference between One-Dimentional and Two-Dimentional Array.
- How to access elements in NumPy.
- Important attributes of NumPy.
- Creating array having all elements Zero and One's
- Basic Math with NumPy
- Important Statistics Functions in NumPy
- How to Split NumPy

<a id="20"></a>
<p style="padding:10px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Table of Contents</p>

    
|No  | Contents |No  | Contents  |
|:---| :---     |:---| :----     |
|1   | [<font color="#254441"> Introduction</font>](#1)                   |8   | [<font color="#254441">Maths with Numpy </font>](#8)   |     
|2   | [<font color="#254441"> 1-D Array</font>](#2)                         |9  | [<font color="#254441">  Array with random values](#9)|      
|3   | [<font color="#254441"> 2-D Array</font>](#3)                     |10  | [<font color="#254441">Min & Max values</font>](#10)   |    
|4   | [<font color="#254441">Slicing</font>](#4)                       |11  | [<font color="#254441">Round Down & Round up</font>](#11)|       
|5   | [<font color="#254441"> Attributes of Numpy</font>](#5)      |12  | [<font color="#254441"> Statistics Functions in NumPy</font>](#12)  |     
|6   | [<font color="#254441"> Data-type conversion</font>](#6)              |13  | [<font color="#254441"> Split Numpy</font>](#13)     |     
|7   | [<font color="#254441"> Array with Zero & One's</font>](#7)                 |   

   

[<h1><font  size=4px> Move to Table of Contents</font></h1>](#20)
<a id="1"></a>
<div class="alert alert-block alert-danger">   
<p style="padding:50px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:50px;text-align:center;border-radius: 00px 00px;overflow:hidden;font-weight:500">1.Introducton</p></div> 

 NumPy stands for 'Numerical Python’. It is an open-source Python library used to perform various mathematical and scientific tasks.It is very important Library for  concentrating on AI 'Artificial intelligence'. Many of its functions are very useful for performing any mathematical or scientific calculation.It's used to support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. As it is known that mathematics is the foundation of machine learning, most of the mathematical tasks can be performed using NumPy.

 <img src="https://miro.medium.com/max/1100/1*1HgaZPEEZcMtgnL_Fq89vQ.webp" alt="Drawing" style="width: 900px; height:300px;"/>
<center>Reference:<a href="https://miro.medium.com/max/1100/1*1HgaZPEEZcMtgnL_Fq89vQ.webp"> image Link</a></center>

<p style="padding:10px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">How to Install Numpy</p>

In [93]:
!pip install numpy 

<div class="alert alert-block alert-warning">
Open Anaconda Prompt and Use the given command to install Numpy Library.
</div>

<p style="padding:10px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">How to Import Numpy</p>

<div class="alert alert-block alert-info">
Ater the installation of Numpy. You can use the Numpy Library by importing it.
</div>

In [20]:
import numpy as np     

[<h1><font  size=2px> Move to Table of Contents</font></h1>](#20)
<a id="2"></a>
<p style="padding:10px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">1-Dimensions Array</p>

NumPy One dimensional array contains only a list. NumPy array is a collection of elements of the same type placed in contiguous memory locations that can be store elements by index number, which is the unique identifier of element.



<img src="https://miro.medium.com/max/1400/1*bjEgmg8gW2P5HsAA1_Z8Ig.webp" alt="Drawing" style="width: 900px; height:300px;"/>
<center>Reference:<a href="https://miro.medium.com/max/1400/1*bjEgmg8gW2P5HsAA1_Z8Ig.webp"> image Link</a></center>

In [64]:
Dimen1=np.array([44,34,12,70,26,61])                              #Create 1-Dimention Array
print('1-Dimention Array:' ,Dimen1)
print('Dimention of Array:',Dimen1.ndim)                               # Check Dimentions of Array by the keyword ".ndim".
print('Type of Array:'     ,type(Dimen1))                               #Check the type of an array

1-Dimention Array: [44 34 12 70 26 61]
Dimention of Array: 1
Type of Array: <class 'numpy.ndarray'>


[<h1><font  size=2px> Move to Table of Contents</font></h1>](#20)
<a id="3"></a>
<p style="padding:10px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">2-Dimensions Array</p>

Two-dimensional array is also know as Matrices which can be represented as collection of rows and columns.Two-Dimentional array contains more than one list. We can convert 1D array into 2D array.


<img src="https://miro.medium.com/max/1400/1*_u4WozjCT3S59mZS0M41lQ.webp" alt="Drawing" style="width: 900px; height:300px;"/>
<center>Reference:<a href="https://miro.medium.com/max/1400/1*_u4WozjCT3S59mZS0M41lQ.webp"> image Link</a></center>

In [65]:
Mul_Dimen=np.arange(10)
a=Mul_Dimen
print(a)
print('Size of Array:',a.size)

[0 1 2 3 4 5 6 7 8 9]
Size of Array: 10


[<h1><font  size=3px> Move to Table of Contents</font></h1>](#20)
<a id="4"></a>
<p style="padding:10px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Slicing in Numpy Array</p>

<img src="https://miro.medium.com/max/1400/1*D_PHnJlbtze5cqMrNngYgw.webp" alt="Drawing" style="width: 900px; height:300px;"/>
<center>Reference:<a href="https://miro.medium.com/max/1400/1*D_PHnJlbtze5cqMrNngYgw.webpp"> image Link</a></center>

In [66]:
a[7]                              # slice elements from array by index number

7

In [67]:
a[1:]                            # print the elements of an array onward from 1 by slicing

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a[1:6]                        # print the elements of an array from 1 to 6 by slicing.

array([1, 2, 3, 4, 5])

[<h1><font  size=3px> Move to Table of Contents</font></h1>](#20)
<a id="5"></a>
<p style="padding:10px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Important Arrays attributes</p>

In [69]:
arr = np.array([[1,2,3],[4,5,6]])  # Show the array length with Rows and Column
print (arr.shape)                  

(2, 3)


In [70]:
Reshape = np.array([[1,2,3],[4,5,6]]) 
print (Reshape.reshape(3,2))        #Resizing the above array with 3 Rows and  2 column. 

[[1 2]
 [3 4]
 [5 6]]


In [71]:
fruit=np.array(['apple','banana','orange','mango'])
print('Total elements in Array:', fruit.size)               # Showing the the number of elements in Array.
print('Bytes per Element:',fruit.itemsize)           #Showing the number of bytes per element.

Total elements in Array: 4
Bytes per Element: 24


In [72]:
arr = np.array([4, 7, 12])       #Create NumPy arrays
arr1 = np.array([5, 9, 15])
con = np.concatenate((arr, arr1)) # Use concatenate() to join two arrays
print(con)


[ 4  7 12  5  9 15]


In [73]:
Sort_array=np.array([1,7,9,4,5,6,2,8,3])     #Sort() function is used to sort the array.
print(np.sort(Sort_array))

[1 2 3 4 5 6 7 8 9]


[<h1><font  size=3px> Move to Table of Contents</font></h1>](#20)
<a id="6"></a>
<p style="padding:10px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500"> Data-Type Convertion in Numpy Array</p>

In [74]:
print(np.array(a,dtype='str'))           # Conversion of element data-Type in Array.

['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']


In [75]:
print(np.array(a,dtype=float))           # Conversion of element data-Type in Array.

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [76]:
np.array(a,dtype=int)             # Conversion of element data-Type in Array.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

[<h1><font  size=3px> Move to Table of Contents</font></h1>](#20)
<a id="7"></a>
<p style="padding:10px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Array having all elements Zero and One's</p>

In [77]:
Zero=np.zeros((10,5))               #Creating an Array with the all element Zero
print(Zero)
print('Dimention of Array:',Zero.ndim  )                          #Check the Dimentions of the array


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Dimention of Array: 2


In [78]:
One=np.ones((12,10))   #Creating an Array with the all element One's
print(One)
print('Dimention of Array:',One.ndim  )                 #Check the Dimentions of the array

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Dimention of Array: 2


In [79]:
full=np.full(12,5)                             #Creating an Array with 12 elements 5.
print(full)
print('Dimention of Array:',full.ndim  )                       #Check the Dimentions of the array

[5 5 5 5 5 5 5 5 5 5 5 5]
Dimention of Array: 1


[<h1><font  size=2px> Move to Table of Contents</font></h1>](#20)
<a id="8"></a>
<p style="padding:10px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Basic Maths with NumPy</p>

In [80]:
math=np.array([1,2,3,4,5])
math1=np.array([6,7,8,9,10])
print('Plus all the elements:',math+math1)        # Plus all the elements of both arrays.
print('Sub all the elements:' ,math-math1)        # Sub all the elements of both arrays.
print('Mul all the elements:' ,math*math1)        # Mul all the elements of both arrays.
print('Div all the elements:' ,math/math1)        # Div all the elements of both arrays.

Plus all the elements: [ 7  9 11 13 15]
Sub all the elements: [-5 -5 -5 -5 -5]
Mul all the elements: [ 6 14 24 36 50]
Div all the elements: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [81]:
Dimen2=np.arange(100).reshape((10,10))
print(Dimen2)
print('Dimention of Array:',Dimen2.ndim)
type(Dimen2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
Dimention of Array: 2


numpy.ndarray

In [82]:
b=Dimen2
print(b)
b[1:2, 2:3]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


array([[12]])

[<h1><font  size=2px> Move to Table of Contents</font></h1>](#20)
<a id="9"></a>
<p style="padding:10px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Array filled with random values</p>

In [83]:
Random_Number=np.random.random(12)     # Create an array with 12 Random Numbers
print(Random_Number)

[0.95215125 0.96914497 0.17088989 0.77533197 0.7848577  0.17322359
 0.85214702 0.72013152 0.3149681  0.90610608 0.69564304 0.76887015]


<div class="alert alert-block alert-info">
    
</div>


In [84]:
Random_int=np.random.randint(1,100,20)
Random_int

array([13, 53, 59, 70, 63, 47, 18, 63, 70, 79, 80, 87, 17, 38, 10, 82, 24,
       22, 59, 77])

<div class="alert alert-block alert-info">
    Print random 20 values between 1 to 100.
</div>


[<h1><font  size=2px> Move to Table of Contents</font></h1>](#20)
<a id="10"></a>
<p style="padding:10px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Minimum and Maximum value from an array</p>

In [85]:
min_max=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(min_max)
print(min_max.min(axis=1))      # Min of each row of array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 1  6 11]


In [86]:
print(min_max.max(axis=0))        # Min of each column of array

[11 12 13 14 15]


[<h1><font  size=2px> Move to Table of Contents</font></h1>](#20)
<a id="11"></a>
<p style="padding:10px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Round down and Round up of elements of an array</p>

In [87]:
                             # Round down
print(np.floor([1.2, 2.5]))
                             # Round up
print(np.ceil([1.2, 2.5]))

[1. 2.]
[2. 3.]


[<h1><font  size=2px> Move to Table of Contents</font></h1>](#20)
<a id="12"></a>
<p style="padding:10px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Important Statistics Functions in NumPy</p>

In [88]:
arr_1 = np.arange(1, 6)
print(arr_1)
#mean
print('Mean:',np.mean(arr_1))
#median
print('Median:',np.median(arr_1))
#average
print('Average:',np.average(arr_1))
# Standard Deviation
print('Standard Deviation:',np.std([4, 6, 3, 5, 2])) 
#variance
print('Variance:',np.var([4, 6, 3, 5, 2]))

[1 2 3 4 5]
Mean: 3.0
Median: 3.0
Average: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


[<h1><font  size=2px> Move to Table of Contents</font></h1>](#20)
<a id="13"></a>
<p style="padding:10px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:150%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Splitting NumPy Arrays</p>

<img src="https://miro.medium.com/max/1400/1*AENBh3KxxiDivXw_QIz8aA.webp" alt="Drawing" style="width: 900px; height:300px;"/>
<center>Reference:<a href="https://miro.medium.com/max/1400/1*AENBh3KxxiDivXw_QIz8aA.webp"> image Link</a></center>

In [89]:
split_array=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.split(split_array,2))

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]



<div class="alert alert-block alert-info">
   Splitting breaks one array into multiple. 
</div>


In [90]:
split_array1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
print(np.split(split_array1,3))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]



<div class="alert alert-block alert-info">
   Multi-Dimentional array breaks into multiple arrays. 
</div>


In [91]:
split_array2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
print(np.hsplit(split_array2,3))

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [92]:
split_array2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
print(np.vsplit(split_array2,3))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]



<div class="alert alert-block alert-info">
   vsplit() function split an array into multiple sub-arrays row-wise.
</div>


# <p style="padding:10px;background-color:#0f0d0d;margin:0;color:#e9c46a;font-family:newtimeroman;font-size:100%;text-align:center;border-radius: 15px 50px;overflow:hidden;font-weight:500">Thank You!</p>
<h3><font color="#254441">If you liked this notebook please upvote. Your feedback will be highly appreciated.</font></h3>
​